language: node_js
node_js: "0.10"
cache:
  apt: true
  directories:
  - node_modules
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq fontforge node ruby1.9.1 ruby1.9.1-dev
  - wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
  - unzip woff-code-latest.zip -d sfnt2woff && cd sfnt2woff && make && sudo mv sfnt2woff /usr/local/bin/ && cd ..
  - rvmsudo gem install fontcustom
  - npm install
script:
  - npm run check
  - scripts/check_build

# Automatically deploys a tagged release to GitHub pages if the Travis build succeeds
after_success: |
  if [ "$TRAVIS_TAG" == "" ]; then
    echo "Not a tagged release, so GitHub pages are not updated!"
  else
    # Config
    masterCommit=`git rev-parse HEAD`
    git config --global user.email "deploy@travis"
    git config --global user.name "Travis CI"
    # This avoids printout of the token when pushing
    git config --global credential.helper store
    echo "https://${GH_USERNAME}:${GH_TOKEN}@github.com" > $HOME/.git-credentials

    printf "\nCloning the gh-pages branch...\n"
    git clone --depth=1 --branch=gh-pages https://github.com/floscher/traffico.git ../traffico-pages

    printf "\nCopy website resources into gh-pages branch...\n"
    cp build/gh-pages/examples.html build/gh-pages/_config.yml ../traffico-pages/
    cp -T build/gh-pages/examples.scss ../traffico-pages/_sass/pages/_examples.scss

    printf "\nCommitting and pushing to gh-pages branch...\n"
    cd ../traffico-pages
    git commit -a -m "Bump gh-pages to $TRAVIS_TAG

  This commit has automatically been crafted by Travis CI based on $masterCommit."
    git push origin gh-pages
    cd ../traffico
  fi
