language: node_js
cache: apt
node_js: "0.10"
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fontforge node ruby1.9.1 ruby1.9.1-dev
  - wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
  - unzip woff-code-latest.zip -d sfnt2woff && cd sfnt2woff && make && sudo mv sfnt2woff /usr/local/bin/ && cd ..
  - rvmsudo gem install fontcustom
  - npm install --global gulp
script:
  - gulp
  - scripts/check_build
