language: node_js
node_js: "0.10"
cache:
  apt: true
  directories:
  - node_modules
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq fontforge node ruby1.9.1 ruby1.9.1-dev
  - wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
  - unzip woff-code-latest.zip -d sfnt2woff && cd sfnt2woff && make && sudo mv sfnt2woff /usr/local/bin/ && cd ..
  - rvmsudo gem install fontcustom
  - npm install
script:
  - gulp
  - scripts/check_build
